name: filcnaplo_kreta_api
publish_to: "none"

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  filcnaplo:
    path: ../filcnaplo/
  http: ^0.13.3
  provider: ^5.0.0
  file_picker: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
